### ISSUE TITLE
hnsw: loadindex segfault

### ISSUE THREAD

**Issue by cdump** [searchivarius/nmslib#145]
Hello!

Mininal example to reproduce the error:
run it first time as is, and run it second time after comment/uncomment saveindex/loadindex lines, as result you'll get `segmentation fault` error

```python
import nmslib_vector
import numpy as np

method = "hnsw"
params = ['M=32', 'post=2', 'efConstruction=800']
q_params = ['ef=1000']

index = nmslib_vector.init("l2", [], method, nmslib_vector.DataType.VECTOR, nmslib_vector.DistType.FLOAT)
nmslib_vector.addDataPoint(index, 1, [0.1, 0.2, 0.3, 0.4])
nmslib_vector.addDataPoint(index, 2, [0.5, 0.6, 0.7, 0.8])

# Build&Save Index
nmslib_vector.createIndex(index, params)
nmslib_vector.saveIndex(index, "test.index")

# Load index
# nmslib_vector.loadIndex(index, "test.index")

nmslib_vector.setQueryTimeParams(index, q_params)
r = nmslib_vector.knnQuery(index, 1, [0.1, 0.2, 0.4, 0.4])
print(r)
```

GDB info
```
Stopped reason: SIGSEGV
0x0000000000d0095f in similarity::Hnsw<float>::SearchCosineNormalizedOld (this=0x12b0c40, query=0x7fffffffdc40) at /home/user/devel/nmslib/similarity_search/src/method/hnsw_distfunc_opt.cc:657
657             query->CheckAndAddToResult(curdist, data_rearranged_[curNodeNum]);

gdb-peda$ p data_rearranged_ 
$1 = std::vector of length 0, capacity 0

gdb-peda$ p curNodeNum 
$2 = 0x0

gdb-peda$ p data_rearranged_[curNodeNum] 
Cannot access memory at address 0x0

gdb-peda$ bt
#0  0x0000000000d0095f in similarity::Hnsw<float>::SearchCosineNormalizedOld (this=0x12b0c40, query=0x7fffffffdc40) at /home/user/devel/nmslib/similarity_search/src/method/hnsw_distfunc_opt.cc:657
#1  0x0000000000b1adf3 in similarity::Hnsw<float>::Search (this=0x12b0c40, query=0x7fffffffdc40) at /home/user/devel/nmslib/similarity_search/src/method/hnsw.cc:686
#2  0x0000000000970477 in main (argc=0x1, argv=0x7fffffffe0c8) at /home/user/devel/nmslib/similarity_search/src/dummy_app.cc:127
#3  0x00007ffff6037830 in __libc_start_main (main=0x96fd56 <main(int, char const**)>, argc=0x1, argv=0x7fffffffe0c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe0b8) at ../csu/libc-start.c:291
#4  0x000000000096fc89 in _start ()
```

Looks like bug was introduced in 37cd6383

**Comment by searchivarius** [comment]
I will have a look shortly, thanks! If this is indeed to the recent change, it will be easy to fix.

**Comment by searchivarius** [comment]
@cdump please, check if this now works (in the master).

**Comment by cdump** [comment]
@searchivarius everything is good now, thank you!
