### ISSUE TITLE
python integration tests

### ISSUE THREAD

**Issue by bluejay9676** [searchivarius/nmslib#221]
Both sparse_bench.py/test_nmslib.py give the following error:
Let's invoke the index-build process
2017-08-03 16:50:52 small_world_rand.cc:348 (CreateIndex) [INFO] NN                  = 17
2017-08-03 16:50:52 small_world_rand.cc:349 (CreateIndex) [INFO] efConstruction_     = 17
2017-08-03 16:50:52 small_world_rand.cc:350 (CreateIndex) [INFO] indexThreadQty      = 4
2017-08-03 16:50:52 small_world_rand.cc:351 (CreateIndex) [INFO] useProxyDist        = 0
2017-08-03 16:50:52 params.h:248 (CheckUnused) [ERROR] Unknown parameter: 'initIndexAttempts'
Traceback (most recent call last):
  File "test_nmslib.py", line 459, in <module>
    test_vector_fresh()
  File "test_nmslib.py", line 140, in test_vector_fresh
    nmslib.createIndex(index, index_param)
RuntimeError: Unknown parameters found!

**Comment by searchivarius** [comment]
Thank you for reporting, these are legacy parameters that are deleted. I will shortly update the test file.

**Comment by searchivarius** [comment]
Thanks again for being vigilant: when I fixed these integration tests they helped me find another recently introduced issue. I believe we are in the clear now, feel free to reopen this, if the issue doesn't resolve.

Don't forget to 
1) pull the code rebuild NMSLIB
2) rebuild / reinstall python bindings
