### ISSUE TITLE
pybind11 import error during nmslib Python installation on mac os

### ISSUE THREAD

**Issue by gokceneraslan** [searchivarius/nmslib#228]
Hi,

When I run `pip install nsmlib` on a mac where pybind11 is not installed, I get `ModuleNotFoundError: No module named 'pybind11'`:

![image](https://user-images.githubusercontent.com/1140359/29162691-76f9d610-7dba-11e7-8ddf-33f21cb975ce.png)

Maybe @benfred can help me with that. I think it's related to this line https://github.com/searchivarius/nmslib/blob/master/python_bindings/setup.py#L107 . 

I'm not familiar with pybind11 but does it even make sense to import a dependency of nmslib in its setup.py?

**Comment by benfred** [comment]
We are using pybind11 to generate the python bindings for this library - it needs to be installed in order to compile the extension, and we import it there to get the header location of the pybind11 library here.

The 'install_requires' line in the setup.py file should install pybind11 + numpy if they aren't already installed:  https://github.com/searchivarius/nmslib/blob/master/python_bindings/setup.py#L136 . 
We delay importing of pybind11 to give this a chance to work.

I tested out uninstalling pybind11 and then installing nmslib from pip and it worked for me

```
Bens-MacBook-Pro-2:python_bindings ben$ pip3 uninstall pybind11
...
   Successfully uninstalled pybind11-2.1.1

Bens-MacBook-Pro-2:python_bindings ben$ pip3 install nmslib
Collecting nmslib
  Downloading nmslib-1.6.3.tar.gz (366kB)
    100% |████████████████████████████████| 368kB 2.6MB/s 
Collecting pybind11>=2.0 (from nmslib)
  Downloading pybind11-2.1.1-py2.py3-none-any.whl (109kB)
    100% |████████████████████████████████| 112kB 5.4MB/s 
Requirement already satisfied: numpy in /usr/local/lib/python3.6/site-packages (from nmslib)
Installing collected packages: pybind11, nmslib
  Running setup.py install for nmslib ... done
Successfully installed nmslib-1.6.3 pybind11-2.1.1
```

I'm unsure why this didn't work for you - maybe I'll try again with miniconda3 instead to see if I can replicate.

In the meantime, if you go 'pip install pybind11' before running this it should work as a workaround

**Comment by benfred** [comment]
I tried again with miniconda - and going ```pip install nmslib``` installed nmslib properly, but it did at one point show the same error message as you before going on to successfully finish the build:

```Bens-MacBook-Pro-2:~ ben$ which pip
/Users/ben/miniconda3/bin/pip
Bens-MacBook-Pro-2:~ ben$ pip install nmslib
Collecting nmslib
  Downloading nmslib-1.6.3.tar.gz (366kB)
    100% |████████████████████████████████| 368kB 164kB/s 
Collecting pybind11>=2.0 (from nmslib)
  Downloading pybind11-2.1.1-py2.py3-none-any.whl (109kB)
    100% |████████████████████████████████| 112kB 225kB/s 
Collecting numpy (from nmslib)
  Downloading numpy-1.13.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.5MB)
    100% |████████████████████████████████| 4.6MB 134kB/s 
Building wheels for collected packages: nmslib
  Running setup.py bdist_wheel for nmslib ... error
  Complete output from command /Users/ben/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T/pip-build-fwv8zdcd/nmslib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T/tmpa5wjf20vpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  creating var
  creating var/folders
  creating var/folders/vv
  creating var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn
  creating var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ben/miniconda3/include -arch x86_64 -I/Users/ben/miniconda3/include -arch x86_64 -I/Users/ben/miniconda3/include/python3.6m -c /var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T/tmp8cr9kwcc.cpp -o var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T/tmp8cr9kwcc.o -std=c++14
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ben/miniconda3/include -arch x86_64 -I/Users/ben/miniconda3/include -arch x86_64 -I/Users/ben/miniconda3/include/python3.6m -c /var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T/tmpygmjb5za.cpp -o var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T/tmpygmjb5za.o -fvisibility=hidden
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T/pip-build-fwv8zdcd/nmslib/setup.py", line 140, in <module>
      zip_safe=False,
    File "/Users/ben/miniconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/ben/miniconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/ben/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/ben/miniconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/Users/ben/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/ben/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/ben/miniconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/ben/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/ben/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/ben/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/build_ext.py", line 77, in run
    File "/Users/ben/miniconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/private/var/folders/vv/z643yw7x7ys6t1yq9whm_0jr0000gn/T/pip-build-fwv8zdcd/nmslib/setup.py", line 109, in build_extensions
      import pybind11
  ModuleNotFoundError: No module named 'pybind11'
  
  ----------------------------------------
  Failed building wheel for nmslib
  Running setup.py clean for nmslib
Failed to build nmslib
Installing collected packages: pybind11, numpy, nmslib
  Running setup.py install for nmslib ... done
Successfully installed nmslib-1.6.3 numpy-1.13.1 pybind11-2.1.1
```

Given that it worked in the end (just displayed an error message half way through), I'm inclined to not worry about this...

**Comment by gokceneraslan** [comment]
Yes, this is printed every time I install nmslib python bindings to a new computer. Maybe adding a `try/except` statement around `import pylib11` would fix it but it's not a big deal as you said. 

Thanks!
