### ISSUE TITLE
Segfault on empty index query in version 1.7.1 @ MacOS

### ISSUE THREAD

**Issue by Dronablo** [searchivarius/nmslib#289]
```
Andrews-iMac:~ andy$ sw_vers -productVersion
10.13.1
Andrews-iMac:~ andy$ python3.6
Python 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import nmslib as NMSLibIndex
>>> print(NMSLibIndex.__version__)
1.7.1
>>> tidx =  NMSLibIndex.init(method='hnsw', space='l2')
>>> tidx.createIndex({'post': 2}, print_progress=False)
>>> tidx.knnQuery(np.array([0,0,0]), k=0)
Segmentation fault: 11
```

**Comment by Dronablo** [comment]
Rechecked version 1.7.2: reproducible at 
MacOS 10.13.1 + python 3.6.3 
`Segmentation fault: 11`
Linux 3.10.0-693.17.1.el7.x86_64 + python 3.6.4
`Ошибка сегментирования (core dumped)`

Trace from linux corefile, if someone need it:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by 'python3.6'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f611b55bc30 in pthread_mutex_lock () from /lib64/libpthread.so.0
Missing separate debuginfos, use: debuginfo-install python36u-3.6.4-1.ius.centos7.x86_64
(gdb) info threads
  Id   Target Id         Frame 
  2    Thread 0x7f6110f66700 (LWP 24621) 0x00007f611b55d945 in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /lib64/libpthread.so.0
* 1    Thread 0x7f611be5b740 (LWP 24581) 0x00007f611b55bc30 in pthread_mutex_lock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007f611b55bc30 in pthread_mutex_lock () from /lib64/libpthread.so.0
#1  0x00007f6108d8951b in __gthread_mutex_lock (__mutex=0x50)
    at /usr/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr-default.h:748
#2  lock (this=0x50) at /usr/include/c++/4.8.2/mutex:134
#3  lock (this=0x7ffebfc59ea0) at /usr/include/c++/4.8.2/mutex:511
#4  unique_lock (__m=..., this=0x7ffebfc59ea0) at /usr/include/c++/4.8.2/mutex:443
#5  similarity::VisitedListPool::getFreeVisitedList (this=0x0) at ./nmslib/similarity_search/include/method/hnsw.h:601
#6  0x00007f6108e28c2d in similarity::Hnsw<float>::baseSearchAlgorithmV1Merge (this=0x1d159b0, query=0x7ffebfc5a660)
    at nmslib/similarity_search/src/method/hnsw.cc:1147
#7  0x00007f6108e29c05 in similarity::Hnsw<float>::Search (this=0x1d159b0, query=<optimized out>)
    at nmslib/similarity_search/src/method/hnsw.cc:698
#8  0x00007f6108bdcbd5 in similarity::IndexWrapper<float>::knnQuery (this=0x1d16510, input=..., k=0) at nmslib.cc:124
#9  0x00007f6108bc5768 in operator() (args#1=<optimized out>, args#0=..., c=<optimized out>, __closure=<optimized out>)
    at /usr/include/python3.6m/pybind11/pybind11.h:72
#10 call_impl<pybind11::object, pybind11::cpp_function::cpp_function(Return (Class::*)(Arg ...), const Extra& ...) [with Return = pybind11::object; Class = similarity::IndexWrapper<float>; Arg = {pybind11::object, long unsigned int}; Extra = {pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, char [370]}]::__lambda12&, 0ul, 1ul, 2ul, pybind11::detail::void_type> (f=..., this=0x7ffebfc5a740) at /usr/include/python3.6m/pybind11/cast.h:1870
#11 call<pybind11::object, pybind11::detail::void_type, pybind11::cpp_function::cpp_function(Return (Class::*)(Arg ...), const Extra& ...) [with Return = pybind11::object; Class = similarity::IndexWrapper<float>; Arg = {pybind11::object, long unsigned int}; Extra = {pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, char [370]}]::__lambda12&> (f=..., this=0x7ffebfc5a740) at /usr/include/python3.6m/pybind11/cast.h:1847
#12 operator() (call=..., __closure=0x0) at /usr/include/python3.6m/pybind11/pybind11.h:155
#13 _ZZN8pybind1112cpp_function10initializeIZNS0_C1INS_6objectEN10similarity12IndexWrapperIfEEIS3_mEINS_4nameENS_9is_methodENS_7siblingENS_3argENS_5arg_vEA370_cEEEMT0_FT_DpT1_EDpRKT2_EUlPS6_S3_mE_S3_ISN_S3_mEIS7_S8_S9_SA_SB_SC_EEEvOSE_PFSD_SG_ESM_ENUlRNS_6detail13function_callEE1_4_FUNESU_ (call=...) at /usr/include/python3.6m/pybind11/pybind11.h:132
#14 0x00007f6108bc5768 in cpp_function<pybind11::object, similarity::IndexWrapper<float>, pybind11::object, unsigned long, pybind11::name, pybind11::is_method, pybind11::sibling, pybind11::arg, pybind11::arg_v, char [370]> (
    f=<optimized out>, this=<optimized out>)
   from /usr/lib64/python3.6/site-packages/nmslib.cpython-36m-x86_64-linux-gnu.so
#15 pybind11::class_<similarity::IndexWrapper<float>>::def<pybind11::object (similarity::IndexWrapper<float>::*)(pybind11::object, unsigned long), pybind11::arg, pybind11::arg_v, char [370]>(char const*, pybind11::object (similarity::IndexWrapper<float>::*&&)(pybind11::object, unsigned long), pybind11::arg const&, pybind11::arg_v const&, char const (&) [370]) (this=<optimized out>, name_=<optimized out>, f=<optimized out>) at /usr/include/python3.6m/pybind11/pybind11.h:1086
#16 0x00007f6108bb9f24 in pybind11::cpp_function::dispatcher (self=<optimized out>, args_in=0x7f61092b4a48, 
    kwargs_in=0x7f611bd92558) at /usr/include/python3.6m/pybind11/pybind11.h:627
#17 0x00007f611b82595f in _PyCFunction_FastCallDict () from /lib64/libpython3.6m.so.1.0
---Type <return> to continue, or q <return> to quit---
#18 0x00007f611b825bb6 in _PyCFunction_FastCallKeywords () from /lib64/libpython3.6m.so.1.0
#19 0x00007f611b89b0c4 in call_function () from /lib64/libpython3.6m.so.1.0
#20 0x00007f611b89c7fe in _PyEval_EvalFrameDefault () from /lib64/libpython3.6m.so.1.0
#21 0x00007f611b89adc5 in _PyEval_EvalCodeWithName () from /lib64/libpython3.6m.so.1.0
#22 0x00007f611b89b2fd in PyEval_EvalCodeEx () from /lib64/libpython3.6m.so.1.0
#23 0x00007f611b89b34b in PyEval_EvalCode () from /lib64/libpython3.6m.so.1.0
#24 0x00007f611b8c62c4 in run_mod () from /lib64/libpython3.6m.so.1.0
#25 0x00007f611b8c83d7 in PyRun_InteractiveOneObjectEx () from /lib64/libpython3.6m.so.1.0
#26 0x00007f611b8c8666 in PyRun_InteractiveLoopFlags () from /lib64/libpython3.6m.so.1.0
#27 0x00007f611b8c8e8e in PyRun_AnyFileExFlags () from /lib64/libpython3.6m.so.1.0
#28 0x00007f611b8dec4d in Py_Main () from /lib64/libpython3.6m.so.1.0
#29 0x0000000000400aee in main ()
```

**Comment by searchivarius** [comment]
Thanks, I will check it out. I can't imagine anyone wanting to run queries on an empty index though :-)
